site_name: Snaketool-Utils

theme:
    name: readthedocs

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
          python:
              options:
                  show_source: false
                  show_root_heading: false

nav:
  - Snaketool_utils: index.md
  - cli_utils: cli_utils.md
